---
address: 0.0.0.0
port: 3000
timeout: 30
log: log/thin.log
max_conns: 1024
require: []

max_persistent_conns: 512
environment: production
servers: 2
daemonize: true
chdir: /var/www/apps/profquotes/current
